- name: set up azure-vm
  hosts: azure-vm-thibault
  remote_user: azureuser
  tasks:
   - name: create folder /pansible
     file:
       path: /home/azureuser/pansible
       state: directory
       mode: '0755'
   - name: copy source files
     copy:
       src: /home/simplon/Bureau/Ansible
       dest: /home/azureuser/pansible
       mode: '0755'
